version: "3.8"

services:
  mysqldb:
    image: mysql:8.1.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: enc3na@@#eng07
      MYSQL_DATABASE: fastfooddb
      MYSQL_USER: italo
      MYSQL_PASSWORD: enc3na@@#eng07
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/fastfooddb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: enc3na@@#eng07
    depends_on:
      - mysqldb

volumes:
  db_data:
