package br.com.portsadapters.fastfoodapp.application.core.domain.enums;

public enum TipoStatus {
	AGUARDANDO_CONFIRMACAO_EMPRESA, 
	AGUARDANDO_COZINHA_INICIAR_PEDIDO_CONFIRMADO, 
	EM_PREPARO,
	PEDIDO_PRODUZIDO_EM_ESPERA_P_ENTREGA, 
	PEDIDO_A_CAMINHO, 
	PEDIDO_ENTREGUE
}
